# This is a basic workflow to help you get started with Actions

name: Testing gource

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
    push:
        branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        name: Setting up gource

        steps:
            - uses: actions/checkout@v2
            - name: Install gource
              run: sudo apt-get install gource xvfb -y
            - name: Install ffmpeg
              run: sudo apt-get update && sudo snap install ffmpeg gifski
            - name: hide display
              run: Xvfb :99.0 -ac -screen 0 1280x720x24 -nolisten tcp &
            - name: mkdir
              run: sudo mkdir -p /tmp/xdg
            - name: XDG runtime
              run: export XDG_RUNTIME_DIR=/tmp/xdg
            - name: SET DISPLAY
              run: export DISPLAY=:99.0
            - name: Run gource with xvfb
              run: xvfb-run gource -1280x720 -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libx264 -preset ultrafast -pix_fmt yuv420p -crf 1 -threads 0 -bf 0 gource.mp4
            - name: create frames dir
              run: mkdir frames
            - name: Create images from video
              run: ffmpeg -i ./gource.mp4  -r 5 frames/%04d.png
            - name: Create gif from images
              run: gifski -o gource.gif ./frames/*.png
            - name: List directory contents
              run: sudo find .
            # - name: setup git
            # run: git add . && git commit --allow-empty --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" && git push origin main
