# This is a basic workflow to help you get started with Actions

name: Testing gource

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
    push:
        branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        name: Setting up gource

        steps:
            - uses: actions/checkout@v2
            - name: Install gource & xvfb
              run: sudo apt-get install gource xvfb -y
            - name: Install ffmpeg & gifski
              run: sudo apt-get update && sudo snap install ffmpeg gifski
            - name: Hide display with xvfb
              run: Xvfb :99 -ac -screen 0 1280x720x24 -nolisten tcp &
            - name: create XDG folder
              run: mkdir -p /tmp/xdg
            - name: set xdg runtime
              run: export XDG_RUNTIME_DIR=/tmp/xdg
            - name: SET DISPLAY
              run: export DISPLAY=:99
            - name: Run gource with xvfb
              run: sudo xvfb-run -a gource -1280x720 -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libx264 -preset ultrafast -pix_fmt yuv420p -crf 1 -threads 0 -bf 0 gource.mp4
            - name: mkdir frames
              run: mkdir frames
            - name: create images from video
              run: ffmpeg -i ./gource.mp4 -r 15 -vf scale=512:-1 frames/%04d.png
            - name: Delete previous gif
              run: rm -f gource.gif
            - name: create gif
              run: gifski -o gource.gif frames/*.png
            - name: remove extras
              run: rm -rf frames gource.mp4
            - name: push to github
              run: git add . && git commit -m "from action" && git push origin main
            - name: list dir
              run: sudo ls -ha
